### ISSUE TITLE
Stairs Climbing

### ISSUE THREAD

**Issue by grassjelly** [hgaren/aliengo_delivery#1]
Hi,

Great job on the software integration of various software module on your project. I'm https://github.com/chvmp/champ 's author and just wondering if I can keep in touch with you?

**Comment by hgaren** [comment]
Hi, 
Thank you for your implementation of mit's code. That  was very helpful for this project. Yes sure, we can keep in touch and talk about stair climbing.
Here is my personal email: e0444217@u.nus.edu

**Comment by grassjelly** [comment]
Thank you! Dropped you an email. Cheers!
