### ISSUE TITLE
Missing "stairs_v3" model

### ISSUE THREAD

**Issue by eborghi10** [hgaren/aliengo_delivery#2]
Hi @hgaren, thanks for sharing this code, it's amazing!

I was wondering where is the missing "stairs_v3" model since the world "elevated_world_ since v2" requires it but I couldn't find it anywhere.

Could you push it to the repo?

Thanks

**Comment by hgaren** [comment]
Dear @eborghi10 , thank you for your interest. 
I have added models named  stairs_v3  and brick_box_3x1x3  in aliengo_gazebo/models. Also changed readme accordingly. Simply you need to copy the files and paste into your local  ~/.gazebo/models directory. While you are launching normal_gazebo.launch , gazebo automatically finds and spawns it. Let me know, if you come up with other issues. 
Regards.

**Comment by eborghi10** [comment]
Thanks, I'll create another PR to remove the necessity of moving the models there.
